### ISSUE TITLE
Fix yaml indentation in the blog

### ISSUE THREAD

**Issue by ehernandez-xk** [vpetersson/rbac-example#1]
tks for the blog.
Role yaml indentation for secrets is incorrect.
https://blog.viktorpetersson.com/2018/06/15/kubernetes-rbac.html

**Comment by vpetersson** [comment]
Good catch. Thanks. Fixed [here](https://github.com/vpetersson/blog.viktorpetersson.com/commit/5df63a23d812c3182559df6c57947062e474836b).
